Toby/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('toby/', include('stats.urls')),
    path('toby/admin/', admin.site.urls),
]

stats/urls.py
from django.urls import path

from . import views

app_name = 'tobystats'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('data/', views.ChartView.as_view(), name='getdata'),
    path('data/<str:since>', views.ChartView.as_view())
]

stats/models.py
from django.db import models

# Create your models here.
"""
class Sample(models.Model):
    #I am not sure if we will use DB model or use plain-text.
    #We probably don't need db, but I'm following the tutorial so it is here for now.
    
    time = models.DateTimeField("time when the sample was made")
    active_1v1 = models.IntegerField(default=0)
    queued_1v1 = models.IntegerField(default=0)
    active_ffa = models.IntegerField(default=0)
    queued_ffa = models.IntegerField(default=0)

    def __str__(self):
        return self.time
"""

stats/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import JsonResponse
from django.views import View
import csv
from datetime import datetime, date, timedelta
import pytz
from collections import defaultdict

# Create your views here.
def convert_datestring_to_dateobj(datestring):
    return datetime.strptime(datestring, "%Y-%m-%d %H:%M:%S").replace(tzinfo=pytz.utc)


class IndexView(View):
    def get(self, request):
        return render(request, 'stats/main.html', {})


class ChartView(View):
    def get_recent_stats(self, most_recent_data):
        age = int((datetime.now(pytz.utc) - convert_datestring_to_dateobj(most_recent_data[0])) / timedelta(minutes=1))
        recent = {
            'data': {
                '1v1m': most_recent_data[1],
                '1v1q': most_recent_data[2],
                'ffam': most_recent_data[3],
                'ffaq': most_recent_data[4]
            },
            'time': {
                'age': age,
                'timestamp': most_recent_data[0]
            }
            
            
        }
        return recent

    def analyze_data(self, since):

        try:
            from_datetime = datetime.strptime(since, '%Y-%m-%d %H:%M:%S')
            from_datetime = from_datetime.replace(tzinfo=pytz.UTC)
        except ValueError:
            return HttpResponse("Couldn't parse time")
        result = {
            '1v1m': [],
            '1v1q': [],
            'ffam': [],
            'ffaq': []
        }
        with open('stats/data/rankedhistory.log', newline='') as f:
            now = datetime.now(pytz.utc)
            data = csv.reader(f)

            for item in data:
                time_raw = item[0]

                #timezone conversion
                time_utc = convert_datestring_to_dateobj(time_raw)

                if(time_utc<from_datetime):
                    continue

                result['1v1m'].append({'time': str(time_utc)[0:-6], 'val': item[1]})
                result['1v1q'].append({'time': str(time_utc)[0:-6], 'val': item[2]})
                result['ffam'].append({'time': str(time_utc)[0:-6], 'val': item[3]})
                result['ffaq'].append({'time': str(time_utc)[0:-6], 'val': item[4]})

            result['recent'] = self.get_recent_stats(item)
            print(result['ffam'][0]['time'])
            return result


    def get(self, request, since="1970-03-02 21:39:40"):
        data = self.analyze_data(since)
        return JsonResponse(data)

stats/templates/stats/base.html
<!DOCTYPE html>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'stats/css/common.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'stats/css/sections.css' %}">
<link rel="shortcut icon" href="{% static 'stats/img/Toby-green.png' %}">
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.13.0/moment.min.js"></script>
<script src="https://d3js.org/d3.v5.js"></script>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript" src="{% static 'stats/scripts/utils.js'%}"></script>

<html>
    <head>
        <title>{% block title %}Toby -- Offworld Ranked Match Stats{% endblock title %}</title>
    </head>
    <body>
        <header>
            <h1>Offworld Ranked Match Stats</h1>
        </header>
        <main>
            {% block main %}{% endblock main %}
        </main>
        <footer>
            <h2>Website designed by <a href="https://github.com/Rhahi">Rhahi</a> and <a href="https://github.com/Trattpingvin/">Trattpingvin</a></h2>
        </footer>
    </body>
</html>

stats/templates/stats/main.html
{% extends 'stats/base.html' %}
{% block main %}
    <div class="section toby">{% include "stats/sections/toby.html" %}</div>
    <div class="section graph-big">{% include "stats/sections/matches.html" %}</div>
    <div class="wrapper">
        <div class="section graph-days">{% include "stats/sections/days.html" %}</div>
        <div class="section graph-time">{% include "stats/sections/time.html" %}</div>
    </div>
{% endblock main %}

stats/templates/stats/sections/matches.html
<meta charset="utf-8">
<div class="button-wrapper create" id="datasetchoosers">
	<button type="button" class="button_creategraph inactive" data-matchtype="ffaq">FFA Queue</button>
	<button type="button" class="button_creategraph active" data-matchtype="ffam">FFA Matches</button>
	<button type="button" class="button_creategraph inactive" data-matchtype="1v1q">1v1 Queue</button>
	<button type="button" class="button_creategraph inactive" data-matchtype="1v1m">1v1 Matches</button>
</div>
<svg width="834" height="500" class="graph"></svg>
<div class="button-wrapper zoom" id="zoomhelpers">
	<button type="button" id="button_zoomday">Zoom to Day</button>
	<button type="button" id="button_zoommonth">Zoom to Month</button>
</div>
Time zone offset:
<select id="tzselect">
	
	
	
</select>
<script>
	$(document).ready(function()
	{
		var tzselect = $("#tzselect");
		var whyisnttimezoneoffsetastaticmethod = new Date();
		if(localStorage.hasOwnProperty('tz')) selected_tz = +localStorage['tz'];
		else selected_tz = Math.floor(whyisnttimezoneoffsetastaticmethod.getTimezoneOffset()/-60);
		for(i=-12;i<15;i++)
		{
			if(i<0) prepend = "";
			else prepend = "+";
			tzselect.append($("<option></option>").attr("value", i).text("UTC " + prepend+i));
		}
		tzselect.val(selected_tz);
	});
	$(".button_creategraph").click(function()
		{
			var buttons = Array.from(document.getElementsByClassName("button_creategraph"));
			buttons.forEach(function(item) {
				item.classList.remove("active");
				item.classList.add("inactive");
			});
			$(this).addClass("active");
			$(this).removeClass("inactive");
			createGraph();
		});
	
	function createGraph() {
		var parseDate = d3.utcParse("%Y-%m-%d %H:%M:%S%Z");
		var timezoneOffset = 0;
		$("#tzselect").off('change');
		$("#tzselect").change(updateDomain);

		function updateDomain()
		{
			var newOffset = $("#tzselect").children("option:selected").val()*60*60*1000;
			data.map(function(d)
			{
				d.time.setTime(d.time.getTime()-timezoneOffset+newOffset);
			});
			x2.domain(d3.extent(data, function(d) { return d.time; }));
			[d1, d2] = x.domain();
			x.domain([d1.setTime(d1.getTime()-timezoneOffset+newOffset), d2.setTime(d2.getTime()-timezoneOffset+newOffset)]);
			focus.select(".area").attr("d", area);
			focus.select(".axis--x").call(xAxis);
			timezoneOffset = newOffset;

		}
		
		

		$("svg").empty();
		
		$("#button_zoomday").off();
		$("#button_zoomday").on("click",
		function()
		{
			zoomToFit(60*60*24);
		});
		
		$("#button_zoommonth").off();
		$("#button_zoommonth").on("click",
		function()
		{
			zoomToFit(60*60*24*30);
		});

		var data_type = $(".button_creategraph.active").attr('data-matchtype');
		
		//data = window.graph_data[data_type];
		data = get_storage_item('graph_data')[data_type];
		if(data===null) alert("Error storing data, localStorage is not available. Try another browser");
		
		
		data.map(d => {
			d.time = parseDate(d.time+"+0000");
			d.val = +d.val;
		});

		
		
		var svg = d3.select("svg"),
		margin = {top: 20, right: 20, bottom: 110, left: 40},
		margin2 = {top: 430, right: 20, bottom: 30, left: 40},
		width = +svg.attr("width") - margin.left - margin.right,
		height = +svg.attr("height") - margin.top - margin.bottom,
		height2 = +svg.attr("height") - margin2.top - margin2.bottom;
		
		
		var x = d3.scaleUtc().range([0, width]),
		x2 = d3.scaleUtc().range([0, width]),
		y = d3.scaleLinear().range([height, 0]),
		y2 = d3.scaleLinear().range([height2, 0]);
		
		var xAxis = d3.axisBottom(x),
		xAxis2 = d3.axisBottom(x2),
		yAxis = d3.axisLeft(y);
		
		var brush = d3.brushX()
		.extent([[0, 0], [width, height2]])
		.on("brush end", brushed);
		
		var zoom = d3.zoom()
		.scaleExtent([1, Infinity])
		.translateExtent([[0, 0], [width, height]])
		.extent([[0, 0], [width, height]])
		.on("zoom", zoomed);
		
		var area = d3.area()
		.curve(d3.curveMonotoneX)
		.x(function(d) { return x(d.time); })
		.y0(height)
		.y1(function(d) { return y(d.val); });
		
		var area2 = d3.area()
		.curve(d3.curveMonotoneX)
		.x(function(d) { return x2(d.time); })
		.y0(height2)
		.y1(function(d) { return y2(d.val); });
		
		svg.append("defs").append("clipPath")
		.attr("id", "clip")
		.append("rect")
		.attr("width", width)
		.attr("height", height);
		
		var focus = svg.append("g")
		.attr("class", "focus")
		.attr("transform", "translate(" + margin.left + "," + margin.top + ")");
		
		var context = svg.append("g")
		.attr("class", "context")
		.attr("transform", "translate(" + margin2.left + "," + margin2.top + ")");
		
		
		
		x.domain(d3.extent(data, function(d) { return d.time; }));
		y.domain([0, d3.max(data, function(d) { return d.val; })]);
		x2.domain(x.domain());
		y2.domain(y.domain());
		
		focus.append("path")
		.datum(data)
		.attr("class", "area")
		.attr("d", area);
		
		focus.append("g")
		.attr("class", "axis axis--x")
		.attr("transform", "translate(0," + height + ")")
		.call(xAxis);
		
		focus.append("g")
		.attr("class", "axis axis--y")
		.call(yAxis);
		
		context.append("path")
		.datum(data)
		.attr("class", "area")
		.attr("d", area2);
		
		context.append("g")
		.attr("class", "axis axis--x")
		.attr("transform", "translate(0," + height2 + ")")
		.call(xAxis2);
		
		context.append("g")
		.attr("class", "brush")
		.call(brush)
		.call(brush.move, x.range());
		
		svg.append("rect")
		.attr("class", "zoom")
		.attr("width", width)
		.attr("height", height)
		.attr("transform", "translate(" + margin.left + "," + margin.top + ")")
		.call(zoom);
		
		
		updateDomain();
		
		
		function brushed() {
			if (d3.event.sourceEvent && d3.event.sourceEvent.type === "zoom") return; // ignore brush-by-zoom
			var s = d3.event.selection || x2.range();
			x.domain(s.map(x2.invert, x2));
			focus.select(".area").attr("d", area);
			focus.select(".axis--x").call(xAxis);
			svg.select(".zoom").call(zoom.transform, d3.zoomIdentity
			.scale(width / (s[1] - s[0]))
			.translate(-s[0], 0));
		}
		
		function zoomed() {
			if (d3.event.sourceEvent && d3.event.sourceEvent.type === "brush") return; // ignore zoom-by-brush
			var t = d3.event.transform;
			var trescaled = t.rescaleX(x2);
			var newdomain = trescaled.domain();
			x.domain(newdomain);
			focus.select(".area").attr("d", area);
			focus.select(".axis--x").call(xAxis);
			context.select(".brush").call(brush.move, x.range().map(t.invertX, t));
		}
		
		function zoomToFit(timespan_seconds)
		{
			[left, right] = x.domain();
			var middle = left.getTime()/2 + right.getTime()/2;
			var half_span = timespan_seconds*1000/2;
			var d1 = new Date(middle - half_span);
			var d2 = new Date(middle + half_span);
			[maxleft, maxright] = x2.domain();
			if(d1<maxleft)
			{
				var diff = maxleft.getTime()-d1.getTime();
				d1 = new Date(maxleft);
				d2.setTime(d2.getTime()+diff);
			} 
			if(d2>maxright)
			{
				var diff = d2.getTime()-maxright.getTime();
				d2=maxright;
				d1.setTime(d1.getTime()-diff);
				if(d1<maxleft) 
				{
					d1=maxleft;
				}
			} 
			x.domain([d1, d2]);
			focus.select(".area").attr("d", area);
			focus.select(".axis--x").call(xAxis);
			context.select(".brush").call(brush.move, [x2(d1), x2(d2)]);
		}
	}
</script>

stats/templates/stats/sections/toby.html
<!-- div section toby -->
<div class="icon" role="img"></div>
<div class="bubble">
    <table>
        <thead>
            <tr>
                <td class="title" colspan="2">
                    Greetings, traveler!<br />
                    Here's the match status.
                </td>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td id="speech-bubble-queue">
                    <!-- No one is waiting in queue. -->
                    <br />
                    Please wait, I am digging up the data...
                </td>
            </tr>
            <tr>
                <td id="speech-bubble-matches">
                    <!-- There are no matches going on right now.-->
                    <br /><br />
                </td>
            </tr>
        </tbody>
    </table>
    <div class="extra" id="speech-bubble-time">
        *
    </div>
</div>

<script>
    function get_storage_item(key, default_val = null)
    {
        if(localStorage.hasOwnProperty(key)) return JSON.parse(localStorage[key]);
        return default_val;
    }
    function set_storage_item(key, val)
    {
        localStorage[key] = JSON.stringify(val);
    }

    function update_data() {
        var latest_data_timestamp = ""
        var graph_data = get_storage_item('graph_data', {
            '1v1m': [],
            '1v1q': [],
            'ffam': [],
            'ffaq': []
        });
        if (graph_data.hasOwnProperty('recent')) latest_data_timestamp = graph_data['recent']['time']['timestamp'];
        else latest_data_timestamp = "1970-04-20 22:33:00";
        let getUrl = "{% url 'tobystats:getdata' %}"+latest_data_timestamp;
        $.get(getUrl, function(django_data) {
            for (var key in django_data){
                if(django_data.hasOwnProperty(key))
                {
                    if(key==="recent")
                    {
                        graph_data['recent'] = django_data[key];
                    }
                    else
                    {
                        django_data[key].map(d => {
                            graph_data[key].push(d);
                        });
                    }
                }
            }
            //window.graph_data = django_data;
            set_storage_item('graph_data', graph_data);
            
            const arrSum = arr => arr.reduce((a, b) => parseInt(a) + parseInt(b), 0);
            if(arrSum(Object.values(django_data['recent']['data'])) === 0) {
                $("#speech-bubble-queue").html(
                'Oh no, there is no one playing ranked!');
                $("#speech-bubble-matches").html("<br />");
            }
            else {
                $("#speech-bubble-queue").html(
                'There are <span class="numbers" id="1v1q">x</span> players \
                in <span class="type">1v1</span> queue<br /> \
                and <span class="numbers" id="ffaq">y</span> players \
                in <span class="type">FFA</span> queue.');
                $("#speech-bubble-matches").html(
                'Currently there are <span class="numbers" id="1v1m">v</span> <span class="type">1v1</span> matches<br /> \
                and <span class="numbers" id="ffam">w</span> <span class="type">FFA</span> matches going on.');
                $("#1v1q").html(django_data['recent']['data']['1v1q']);
                $("#1v1m").html(django_data['recent']['data']['1v1m']);
                $("#ffaq").html(django_data['recent']['data']['ffaq']);
                $("#ffam").html(django_data['recent']['data']['ffam']);
            }
            $("#speech-bubble-time").html('*this status is based on the query made <span id="query_age">z</span> minutes ago*');
            $("#query_age").html(django_data['recent']['time']['age']);
            createGraph();
        });
    };
    
    window.onload = update_data;
</script>